{{- if eq .Values.database.type "internal" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fichador.fullname" . }}-db
  labels:
    {{- include "fichador.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fichador.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "fichador.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgres
          image: {{ .Values.database.internal.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.internal.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.internal.password }}
            - name: POSTGRES_DB
              value: {{ .Values.database.internal.dbName }}
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
        {{- if .Values.database.internal.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "fichador.fullname" . }}-db-pvc
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}