{{- if and (eq .Values.database.type "internal") .Values.database.internal.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fichador.fullname" . }}-db-pvc
  labels:
    {{- include "fichador.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.internal.persistence.size }}
{{- end }}